<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SNSBACKUPASANI01" failures="0" tests="8" name="qaautomation.august2021.APITest" time="0.029" errors="1" timestamp="2021-09-19T09:51:05 WIB" skipped="7">
  <testcase classname="qaautomation.august2021.APITest" name="fakerEmail" time="0.000">
    <skipped/>
  </testcase> <!-- fakerEmail -->
  <system-out/>
  <testcase classname="qaautomation.august2021.APITest" name="incorrectLoginAPI" time="0.000">
    <skipped/>
  </testcase> <!-- incorrectLoginAPI -->
  <system-out/>
  <testcase classname="qaautomation.august2021.APITest" name="testLoginAPI" time="0.029">
    <error type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
at qaautomation.august2021.BaseAPITest.testLoginAPI(BaseAPITest.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because the return value of "java.lang.System.getProperty(String)" is null
at qaautomation.august2021utils.DataUtility.<clinit>(DataUtility.java:20)
... 20 more
]]>
    </error>
  </testcase> <!-- testLoginAPI -->
  <system-out/>
  <testcase classname="qaautomation.august2021.APITest" name="configAPI" time="0.000">
    <skipped/>
  </testcase> <!-- configAPI -->
  <system-out/>
  <testcase classname="qaautomation.august2021.APITest" name="dashboardAPIWithSchema" time="0.000">
    <skipped/>
  </testcase> <!-- dashboardAPIWithSchema -->
  <system-out/>
  <testcase classname="qaautomation.august2021.APITest" name="configAPI2" time="0.000">
    <skipped/>
  </testcase> <!-- configAPI2 -->
  <system-out/>
  <testcase classname="qaautomation.august2021.APITest" name="userAPI" time="0.000">
    <skipped/>
  </testcase> <!-- userAPI -->
  <system-out/>
  <testcase classname="qaautomation.august2021.APITest" name="dashboardAPI" time="0.000">
    <skipped/>
  </testcase> <!-- dashboardAPI -->
  <system-out/>
</testsuite> <!-- qaautomation.august2021.APITest -->
