<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SNSBACKUPASANI01" failures="1" tests="8" name="qaautomation.august2021.APITest" time="2.774" errors="0" timestamp="18 Sept 2021 07:01:17 GMT" skipped="7">
  <testcase classname="qaautomation.august2021.APITest" name="dashboardAPIWithSchema" time="0.000">
    <skipped/>
  </testcase> <!-- dashboardAPIWithSchema -->
  <testcase classname="qaautomation.august2021.APITest" name="configAPI" time="0.000">
    <skipped/>
  </testcase> <!-- configAPI -->
  <testcase classname="qaautomation.august2021.APITest" name="incorrectLoginAPI" time="0.000">
    <skipped/>
  </testcase> <!-- incorrectLoginAPI -->
  <testcase classname="qaautomation.august2021.APITest" name="configAPI2" time="0.000">
    <skipped/>
  </testcase> <!-- configAPI2 -->
  <testcase classname="qaautomation.august2021.APITest" name="testLoginAPI" time="2.774">
    <failure message="expected [200] but found [422]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [422]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at qaautomation.august2021.BaseAPITest.testLoginAPI(BaseAPITest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </failure>
  </testcase> <!-- testLoginAPI -->
  <testcase classname="qaautomation.august2021.APITest" name="fakerEmail" time="0.000">
    <skipped/>
  </testcase> <!-- fakerEmail -->
  <testcase classname="qaautomation.august2021.APITest" name="userAPI" time="0.000">
    <skipped/>
  </testcase> <!-- userAPI -->
  <testcase classname="qaautomation.august2021.APITest" name="dashboardAPI" time="0.000">
    <skipped/>
  </testcase> <!-- dashboardAPI -->
</testsuite> <!-- qaautomation.august2021.APITest -->
